import Layout from "@/components/layout";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "../styles/globals.css";
import Script from "next/script";

const PoppinsFont = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Nex Product",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${PoppinsFont.className} antialiased bg-[#e2eafc] dark:bg-[#082025] duration-300`}
      >
        <Layout>{children}</Layout>
        <Script
          src="https://kit.fontawesome.com/79a164c540.js"
          crossOrigin="anonymous"
        ></Script>
      </body>
    </html>
  );
}
